### ISSUE TITLE
Select Room/Table Page- Close tabs get hidden

### ISSUE THREAD

**Issue by RanekarSheetal** [SolutionsD2D/POS-#18]
In Mozilla Browser with Responsive Design View 1024*768

Steps to Reproduce:

1.When user opens the browser.
2.Enter POS Valid Url.
3.Enter valid username and password.
4.Click Login button.
5.Dashboard displayed with bydefault messaging page.
6.Click Point of Sale tab.
7.Select POS user and click New session tab.
8.Click Validate and Open session tab.
9.Room page is displayed with cash drawer popoview.
10.Enter reason and amount > click accept button.
11.Click Happy Hours.
12.Close Happy Hours tab is enabled

Actual : Close tab get hidden by table area view controller.

Expected:Close tab should not get hidden by table area view controller.
Refer this issue
![close button](https://cloud.githubusercontent.com/assets/12234741/7674928/31ace162-fd4f-11e4-8a6c-821c4617f486.png)

**Comment by Siddharthrjain** [comment]
close button will not behidden

**Comment by RanekarSheetal** [comment]
Issue fixed.
