### ISSUE TITLE
Select Room/Table Page- Incorrect information displays in left side

### ISSUE THREAD

**Issue by RanekarSheetal** [SolutionsD2D/POS-#20]
In Mozilla Browser with Responsive Design View 1024*768

Steps to Reproduce:

1.When user opens the browser.
2.Enter POS Valid Url.
3.Enter valid username and password.
4.Click Login button.
5.Dashboard displayed with bydefault messaging page.
6.Click Point of Sale tab.
7.Select POS user and click New session tab.
8.Click Validate and Open session tab.
9.Room page is displayed with cash drawer popoview.
10.Enter reason and amount > click accept button.
11.Select Room/Table page displays with incorrect information displays in left side.

Actual : Left panel does not displays correct information of  the following Open Session, Current No., occupied table, empty table , administrator and notifications 

Expected:Room tab should display vertical scrollbar.
Refer this issue
![room page](https://cloud.githubusercontent.com/assets/12234741/7675046/ee8e803c-fd50-11e4-959f-ff8785d70dd0.png)

**Comment by rcksolapur** [comment]
plz check

**Comment by RanekarSheetal** [comment]
Issue fixed.
