### ISSUE TITLE
Select Table/Room page-Issue in tabs.

### ISSUE THREAD

**Issue by RanekarSheetal** [SolutionsD2D/POS-#25]
In Mozilla Browser with Responsive Design View 1024*768

Steps to Reproduce:

1.When user opens the browser.
2.Enter POS Valid Url.
3.Enter valid username and password.
4.Click Login button.
5.Dashboard displayed with by default messaging page.
6.Click Point of Sale tab.
7.Select POS user and click New session tab.
8.Click Validate and Open session tab.
9.Room page is displayed with cash drawer popover view.
10.Enter reason and amount > click accept button.
11.Room 1 displayed with number of tables.

Actual: Consistency of tabs is in incorrect layout.

Expected:It should be aligned in center with proper layout
Refer this issue
![1](https://cloud.githubusercontent.com/assets/12234741/7710895/9bc8e01a-fe84-11e4-9788-cb16819b8909.png)

**Comment by Siddharthrjain** [comment]
@RanekarSheetal issue has been resolved no button will get hide

**Comment by RanekarSheetal** [comment]
Issue fixed.
