### ISSUE TITLE
Design Issue

### ISSUE THREAD

**Issue by RanekarSheetal** [SolutionsD2D/POS-#27]
Expected :Tabs should displays in proper layout and same size in a line, it should not get hidden by product list screen.

![tabs](https://cloud.githubusercontent.com/assets/12234741/7868477/f375d9a0-0599-11e5-95cd-7303131c841c.png)

**Comment by Siddharthrjain** [comment]
@RanekarSheetal issue has been resolved

**Comment by RanekarSheetal** [comment]
Issue fixed.
