### ISSUE TITLE
Design Issue-Layout and Formatting

### ISSUE THREAD

**Issue by RanekarSheetal** [SolutionsD2D/POS-#30]
Suggestion: Design and Layout issues in Select Table/Room page in Left side.
![scrollbar](https://cloud.githubusercontent.com/assets/12234741/7726852/80bbccbc-ff22-11e4-85ec-84a9caec0236.png)

**Comment by rcksolapur** [comment]
left panle issue is resovled and for selection of room drop down menu it seems to be brower releated issue but it works fine on firfox

**Comment by RanekarSheetal** [comment]
@rcksolapur   Issue Fixed.Hence closed.
