### ISSUE TITLE
Report gets hidden

### ISSUE THREAD

**Issue by RanekarSheetal** [SolutionsD2D/POS-#33]
In Mozilla Browser with Responsive Design View 1024*768

Steps to Reproduce:

1.When user opens the browser.
2.Enter POS Valid Url.
3.Enter valid username and password.
4.Click Login button.
5.Dashboard displayed with bydefault messaging page.
6.Click Point of Sale tab.
7.Select POS user and click New session tab.
8.Click Validate and Open session tab.
9.Room page is displayed with cash drawer popoview.
10.Enter reason and amount > click accept button.
11.Select Room tab> Select Table >Select Product>Make cash payment.
12.Click Print button.
13.Filling station page displays with report.

Actual : Filling station report gets hidden due to Next Order and Exit POS tabs..

Expected:Filling station report does not get hidden by Next Order and Exit POS tabs.
Refer this issue
![filling station]
![filling station](https://cloud.githubusercontent.com/assets/12234741/7726702/707a7408-ff21-11e4-8ec2-06d847d3305c.png)

**Comment by Siddharthrjain** [comment]
@issue has been resolved while scrolling you can see whole report

**Comment by RanekarSheetal** [comment]
Issue fixed.
