### ISSUE TITLE
Edit Functionality

### ISSUE THREAD

**Issue by RanekarSheetal** [SolutionsD2D/POS-#36]
In Mozilla Browser with Responsive Design View 1024*768

Steps to Reproduce:

1.When user opens the browser.
2.Enter POS Valid Url.
3.Enter valid username and password.
4.Click Login button.
5.Dashboard displayed with by default messaging page.
6.Click Point of Sale tab.
7.Select POS user and click New session tab.
8.Click Validate and Open session tab.
9.Room page is displayed with cash drawer popover view.
10.Enter reason and amount > click accept button.
11.Room 1 displayed with number of tables.
12.Click on Edit button.
13.Move/adjust tables wherever you want.

Actual:It redirects towards selected table make order page

Expected:It should remain same on select room page .

![table 2](https://cloud.githubusercontent.com/assets/12234741/7733338/1319219e-ff4c-11e4-8a20-4dbd12d3a729.png)

**Comment by Siddharthrjain** [comment]
@RanekarSheetal issue has been resolved

**Comment by RanekarSheetal** [comment]
Issue fixed.
