### ISSUE TITLE
Select Product Page-when selects product runtime error displays.

### ISSUE THREAD

**Issue by RanekarSheetal** [SolutionsD2D/POS-#37]
In Mozilla Browser with Responsive Design View 1024*768

Steps to Reproduce:

1.When user opens the browser.
2.Enter POS Valid Url.
3.Enter valid username and password.
4.Click Login button.
5.Dashboard displayed with by default messaging page.
6.Click Point of Sale tab.
7.Select POS user and click New session tab.
8.Click Validate and Open session tab.
9.Room page is displayed with cash drawer popover view.
10.Enter reason and amount > click accept button.
11.Room 1 displayed with number of tables.
12.Select Room > Select Table > Select Product.

Actual:Runtime error message is displayed.

Expected:It should display selected product amount in total amount bill
![order1](https://cloud.githubusercontent.com/assets/12234741/7777436/977969a4-00e0-11e5-94e5-fc2b3896d608.png)
![order2](https://cloud.githubusercontent.com/assets/12234741/7777440/a040aebc-00e0-11e5-9744-79e908013b49.png)

**Comment by shridhargharpure** [comment]
The issue is resolve

**Comment by RanekarSheetal** [comment]
Issue Fixed.
