### ISSUE TITLE
Select Table page-Close Happy Hours gets hidden by save button.

### ISSUE THREAD

**Issue by RanekarSheetal** [SolutionsD2D/POS-#38]
In Mozilla Browser with Responsive Design View 1024*768

Steps to Reproduce:

1.When user opens the browser.
2.Enter POS Valid Url.
3.Enter valid username and password.
4.Click Login button.
5.Dashboard displayed with bydefault messaging page.
6.Click Point of Sale tab.
7.Select POS user and click New session tab.
8.Click Validate and Open session tab.
9.Room page is displayed with cash drawer popoview.
10.Enter reason and amount > Click accept button.
11.Select Room/Table Detail page.
12.Click Edit button.
13.Save and cancel tabs enabled.
14.Close Happy Hours gets hidden by save button.

Actual : Close Happy Hours gets hidden by save button.

Expected: Close Happy Hours should not get hidden by save button.
Refer this
![save](https://cloud.githubusercontent.com/assets/12234741/7837385/39e46c36-04a4-11e5-8a4c-e97c41bc1f04.png)

**Comment by Siddharthrjain** [comment]
issue resolved save cancel will be displayed beside of happy hours

**Comment by RanekarSheetal** [comment]
Issue fixed.
