### ISSUE TITLE
Select Product Page-Print tab gets half hidden by Close Happy Hours.

### ISSUE THREAD

**Issue by RanekarSheetal** [SolutionsD2D/POS-#39]
In Mozilla Browser with Responsive Design View 1024*768

Steps to Reproduce:

1.When user opens the browser.
2.Enter POS Valid Url.
3.Enter valid username and password.
4.Click Login button.
5.Dashboard displayed with by default messaging page.
6.Click Point of Sale tab.
7.Select POS user and click New session tab.
8.Click Validate and Open session tab.
9.Room page is displayed with cash drawer popover view.
10.Enter reason and amount > click accept button.
11.Select Room/Table page > Click Edit button.
12.Click save button
13.Pop msg displays "Record Updated" 
14.Select Room1 > Select Table.

Actual:1.Print tab gets half hidden by Close Happy Hours.
           2.Cancel and Save button needs to be in same layout and same size.

Expected:1.Print tab should not get hidden by Close Happy Hours.
                2.Cancel and Save button should be in same layout and same size.

Refer this
![design ui issues](https://cloud.githubusercontent.com/assets/12234741/7837334/f9a4b108-04a3-11e5-94cb-ec76209408a9.png)

**Comment by Siddharthrjain** [comment]
issue has been resolved there will be no save and cacel button edit page

**Comment by RanekarSheetal** [comment]
Issue fixed.
