### ISSUE TITLE
Table Detail Page - Split,Merge and Print tabs gets hidden 

### ISSUE THREAD

**Issue by RanekarSheetal** [SolutionsD2D/POS-#4]
In Mozilla Browser with Responsive Design View 1024*768

Steps to Reproduce:

1.When user opens the browser.
2.Enter POS Valid Url.
3.Enter valid username and password.
4.Click Login button.
5.Dashboard displayed with bydefault messaging page.
6.Click Point of Sale tab.
7.Select POS user and click New session tab.
8.Click Validate and Open session tab.
9.Room page is displayed with cash drawer popoview.
10.Enter reason and amount > click accept button.
11.Select room.
12.Select table > Table Detail page.

Actual : Split,Merge and Print tabs gets hidden by table area view controller.

Expected:Split,Merge and Print tabs should not get hidden by table area view controller.
Refer this issue
![tabs](https://cloud.githubusercontent.com/assets/12234741/7667024/c4281d82-fc18-11e4-9419-7f3dc7758053.png)

**Comment by Siddharthrjain** [comment]
Has been resolved on 251

**Comment by RanekarSheetal** [comment]
Issue Fixed.
