### ISSUE TITLE
Sale Detail-Design Issue

### ISSUE THREAD

**Issue by RanekarSheetal** [SolutionsD2D/POS-#44]
Expected:Need to be in center alignment

![center alignment](https://cloud.githubusercontent.com/assets/12234741/7837843/38532328-04a7-11e5-9ba2-add638d3d977.png)

![sale detail](https://cloud.githubusercontent.com/assets/12234741/7868123/8a37f718-0597-11e5-8136-a6f090d510a5.png)

**Comment by Siddharthrjain** [comment]
@RanekarSheetal Issue has been resolved

**Comment by RanekarSheetal** [comment]
Issue fixed.
