### ISSUE TITLE
Happy Hours- get hidden by change tab

### ISSUE THREAD

**Issue by RanekarSheetal** [SolutionsD2D/POS-#46]
Actual:Happy Hours tab is get hidden due to Change tab.

Expected:Happy Hours tab should not be hidden due to Change tab.

![happy hours](https://cloud.githubusercontent.com/assets/12234741/7838467/aea7d8a4-04aa-11e5-8d79-0a0c2a1ee61e.png)

**Comment by Siddharthrjain** [comment]
issue has been resolved

**Comment by RanekarSheetal** [comment]
Issue fixed.
