### ISSUE TITLE
Select Product Page- Merge screen displays after click on Split tab.

### ISSUE THREAD

**Issue by RanekarSheetal** [SolutionsD2D/POS-#47]
Steps:
1.When user click on split tab.
2.It displays Merge screen.

Actual: 1.Merge screen displays.
            2.Happy Hours tab gets hidden by change tab

Expected:It should display Split screen.

![merge screen](https://cloud.githubusercontent.com/assets/12234741/7838480/c16fdfa4-04aa-11e5-8f02-87741a9201be.png)

**Comment by Siddharthrjain** [comment]
@RanekarSheetal issue has been resolved on 28th may

**Comment by RanekarSheetal** [comment]
Issue fixed.
