### ISSUE TITLE
Select Product Page- Split screen displays after click on change tab.

### ISSUE THREAD

**Issue by RanekarSheetal** [SolutionsD2D/POS-#48]
Steps:
1.When user click on change tab.
2.It displays split screen.

Actual: 1.Split screen displays.

Expected:It should display change screen.
![change1](https://cloud.githubusercontent.com/assets/12234741/7838839/c66b162a-04ac-11e5-8a8d-f1d1cef3171a.png)

**Comment by Siddharthrjain** [comment]
@RanekarSheetal issue has been resolved

**Comment by RanekarSheetal** [comment]
Issue fixed.
