### ISSUE TITLE
Select Room/Table Page-Issue in Popup message

### ISSUE THREAD

**Issue by RanekarSheetal** [SolutionsD2D/POS-#6]
In Mozilla Browser with Responsive Design View 1024*768

Steps to Reproduce:

1.When user opens the browser.
2.Enter POS Valid Url.
3.Enter valid username and password.
4.Click Login button.
5.Dashboard displayed with bydefault messaging page.
6.Click Point of Sale tab.
7.Select POS user and click New session tab.
8.Click Validate and Open session tab.
9.Room page is displayed with cash drawer popoview.
10.Enter reason and amount > click accept button.
11.Select Room/Table Detail page.
12.Click Edit button.
13.Save and cancel tabs enabled.
14.Click Save button.

Actual : Popup message displays as "update ok" with "Ok" button.

Expected: Popup message should displays as "Record Updated" with "Ok" button.
Refer this
![save popup 4](https://cloud.githubusercontent.com/assets/12234741/7667146/bcf0d6aa-fc1b-11e4-8563-7b152d24e6a0.png)

**Comment by Siddharthrjain** [comment]
@RanekarSheetal Hello Shetal the bug has been resolved with message racord updated

**Comment by RanekarSheetal** [comment]
Issue Fixed.
